services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: odonto-manage
    ports:
      - "8080:8080"
    networks:
      - odonto-net
    depends_on:
      - db
    image: lgmleite/odonto-manage-api:v0.0.3

  db:
    image: 'postgres:latest'
    container_name: odonto-manage-database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: odonto
      POSTGRES_PASSWORD: leader066
      POSTGRES_DB: odonto-manage-dev

networks:
  odonto-net:
    driver: bridge

volumes:
  postgres_data:
    
# url do rider: Server=dpg-crd5lgt2ng1s73folq4g-a.oregon-postgres.render.com;Port=5432;Database=odonto_manage_database;User Id=odonto_manage_database_user;Password=A0juCYHCaOPwBNgtoZa2hqJziw13pPt9
