services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: odonto-manage
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - odonto-net
    depends_on:
      - db
  db:
    image: 'postgres:latest'
    container_name: odonto-manage-database
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: odonto-manage
    

networks:
  odonto-net:
    driver: bridge

volumes:
  postgres_data: